# Generated by Django 5.2.8 on 2026-01-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
    ]
